### ISSUE TITLE
rtnl_link_add tun0: Invalid input data or parameter

### ISSUE THREAD

**Issue by LZHHZLLZH** [SiliconLabs/wisun-br-linux#5]
I tried to run wsbrd on a mips-core platform, but I got the following error:
rtnl_link_add tun0: Invalid input data or parameter
I tried to use "ip tuntap add dev tap0 mod tap" command directly, and it works. Therefore, I don't know why this error occurs. I used libnl3.7 and libnl3.2.26, but both have this problem

**Comment by MathisMARION** [comment]
Hello, we have managed to reproduce the issue using QEMU and `libnl` version 3.4. In the meantime you should be able to run `wsbrd` by configuring manually your network interface as described in the section "Running wsbrd Without Root Privilege" of the `README`. This issue may be caused by `libnl`.

**Comment by MathisMARION** [comment]
Just to keep you up to date, the error I was getting turned out to be caused by the emulator missing some endianness conversions. I submitted a couple patches to QEMU, which [are now integrated](https://gitlab.com/qemu-project/qemu/-/commits/master?search=Mathis+Marion). This means that we cannot reproduce your issue however, I hope it is not critical.
